scorecard: Update to v5.4.0 (#7)
Since v5.3.0, scorecard skips dangling symlinks and detects
symlink path traversal when run on local files

That resolved bootc repo error:
Error: check runtime error: Binary-Artifacts: internal error:
error during ListFiles: error walking the path ".": stat
baseimage/base/ostree: no such file or directory

Signed-off-by: Xiaofeng Wang <henrywangxf@me.com>